country_name: Ruritania
country_code: RU
view_state:
  longitude: 18.51
  latitude: -34.02
  zoom: 10
ecosystem_gee_asset:
  id: projects/goog-rle-assessments/assets/ruritania/ruritania_ecosystems
  ecosystem_column: ECO_CODE
  functional_group_column: EFG1